version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

sphinx:
  configuration: module_4/docs/source/conf.py

python:
  install:
    - requirements: module_4/docs/requirements.txt
    - method: pip
      path: module_4