name: Module 4 Tests

on:
  workflow_call:  # This makes the workflow reusable

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/module_4
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: jhudb_gradrec
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        pip install pytest pytest-cov
        pip install -e .

    - name: Setup test environment
      run: |
        # Create data directory
        mkdir -p src/data
        # Set environment variables
        echo "TEST_ENV=True" >> $GITHUB_ENV
        echo "USE_SAMPLE_HTML=1" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_WORKSPACE/module_4" >> $GITHUB_ENV

    - name: Setup database and user
      run: |
        PGPASSWORD='' psql -h localhost -U postgres -p 5433 -c 'DROP DATABASE IF EXISTS jhudb_gradrec;'
        PGPASSWORD='' psql -h localhost -U postgres -p 5433 -c 'DROP USER IF EXISTS jhuuser;'
        PGPASSWORD='' psql -h localhost -U postgres -p 5433 -c 'CREATE USER jhuuser WITH LOGIN CREATEDB;'
        PGPASSWORD='' psql -h localhost -U postgres -p 5433 -c 'CREATE DATABASE jhudb_gradrec OWNER jhuuser;'
        PGPASSWORD='' psql -h localhost -U postgres -p 5433 -c 'GRANT ALL PRIVILEGES ON DATABASE jhudb_gradrec TO jhuuser;'

    - name: Run tests with pytest
      env:
        TEST_ENV: "True"
        DATABASE_URL: "postgresql://jhuuser@localhost:5433/jhudb_gradrec"
      run: |
        pytest --cov=src/ --cov-report=xml -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: Build documentation
      run: |
        cd docs
        make html